name: "dbt"
version: "1.0.0"
config-version: 2

profile: "local"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

log-path: logs
packages-install-path: packages
target-path: "target"

clean-targets: # dbt clean
    - "target"
    - "dbt_packages"

models:
    dbt:
        example:
            +materialized: view
        business:
            +schema: business
