apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: postgres-secret
data:
    username: dXNlcg== # user
    password: c2VjcmV0 # secret
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: postgres-cluster
spec:
    instances: 1
    bootstrap:
        initdb:
            database: test
            owner: user
            secret:
                name: postgres-secret
    storage:
        size: 1Gi
